[Mainnet] ICO Contract
stratisproject/CirrusSmartContracts pull request #26
Opened 2020-12-31 07:55 UTC by YakupIpek

# ICO Smart Contract

**Compiler**
```
v0.0.2
```

**Contract Hash**
```
c73be12ffc41a1e41871bc14aba7b9c2175cbc9e0cfb6fc4c341baaf7550193b
```

**Contract Byte Code**
```
4D5A90000300000004000000FFFF0000B800000000000000400000000000000000000000000000000000000000000000000000000000000000000000800000000E1FBA0E00B409CD21B8014CCD21546869732070726F6772616D2063616E6E6F742062652072756E20696E20444F53206D6F64652E0D0D0A2400000000000000504500004C0102001168BE8B0000000000000000E00022200B013000004A000000020000000000002E68000000200000008000000000001000200000000200000400000000000000040000000000000000A000000002000000000000030040850000100000100000000010000010000000000000100000000000000000000000DC6700004F000000000000000000000000000000000000000000000000000000008000000C000000C06700001C0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000200000080000000000000000000000082000004800000000000000000000002E746578740000003448000000200000004A000000020000000000000000000000000000200000602E72656C6F6300000C0000000080000000020000004C000000000000000000000000000040000042000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010680000000000004800000002000500803A0000402D000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004602280600000A72010000706F0700000A2A4A02280600000A7201000070036F0800000A2A4602280600000A72130000706F0900000A2A4A02280600000A7213000070036F0A00000A2A4602280600000A722D0000706F0900000A2A4A02280600000A722D000070036F0A00000A2A4602280600000A72430000706F0900000A2A4A02280600000A7243000070036F0A00000A2A4602280600000A725F0000706F0700000A2A4A02280600000A725F000070036F0800000A2A4602280600000A72790000706F0B00000A2A4A02280600000A7279000070036F0C00000A2A8202280100000602280D00000A6F0E00000A370B022809000006166AFE032A162A4602280600000A729F0000706F0900000A2A4A02280600000A729F000070036F0A00000A2A4602280600000A72AB0000706F0100002B2A4A02280600000A72AB000070036F1000000A2A00000013300500D3000000010000110203281100000A020519FE0572C30000707215010070281200000A281300000A0202280600000A0E076F1400000A7229010070281300000A02281500000A0E096F0200002B0A0206281C000006050B02070E040E050E0628130000060C02086F1700000A7277010070281300000A021203FE15090000021203086F1800000A7D0800000409280300002B020E072806000006020E08280800000602086F1800000A2804000006020718FE01280C0000060202280B0000062D040E042B02156A280A0000060204280F0000060206281A0000062A00133006006900000000000000032C0603172E252B4602166A198D0B0000012516048C15000001A2251705A225180E04A2166A280400002B2A02166A198D0B0000012516048C15000001A2251705A225180E04A2166A280500002B2A02166A188D0B000001251605A225170E04A2166A280600002B2A22022815000006262A00001330080026010000020000110202280D00000672B7010070281300000A0202281B00000A6F1C00000A166AFE0372E3010070281300000A02281600000602281D0000060A02280B0000062D07722F0200702B0572450200700B02022803000006166A07188D0B000001251602281B00000A6F1D00000A8C07000001A22517067B070000048C15000001A2166A281E00000A0C02086F1F00000A2C0D086F2000000AA5170000012B01167255020070281300000A021203FE150A000002120302281B00000A6F1D00000A7D090000041203067B050000047D0A0000041203067B070000047D0B0000041203067B060000047D0C00000409280700002B02022809000006067B07000004DB280A000006067B06000004166A36180202281B00000A6F1D00000A067B06000004282100000A26172A000013300800C90000000300001102022807000006166A7283020070178D0B000001251602281B00000A6F1D00000A8C07000001A2166A281E00000A0A066F1F00000A3982000000066F2000000A0C08750700000114FE03252D0B1203FE1507000001092B0608A5070000010B2C5B077E2200000A282300000A2C4E02022805000006166A72AB020070188D0B0000012516078C07000001A22517198C18000001A2166A281E00000A0A02066F1F00000A2C0B066F2000000A14FE032B011672BD020070281300000A2A021672F1020070281300000A2A000000133003004D000000000000000202281B00000A6F1D00000A02280E000006282400000A7229030070281300000A0202280D00000616FE017279030070281300000A0202280E00000602282500000A282100000A6F1F00000A2A00000013300800BB000000040000110202280B00000616FE0172A50300707215040070281200000A281300000A0202281B00000A6F1D00000A02280E000006282400000A7233040070281300000A0202280D00000616FE017279030070281300000A02022803000006166A722F020070188D0B000001251602281B00000A6F1D00000A8C07000001A225170228090000068C15000001A2166A281E00000A0A02166A280A00000602066F1F00000A2C0D066F2000000AA5170000012B01167255020070281300000A172A00133002003E000000050000111200FE15070000020228100000060B160C2B230708A3070000020D097B0300000402280D00000A6F0E00000A3704090A2B0A0817580C08078E6932D7062A00001330040026000000060000110203281B0000060A020628110000060206068E6917DA8F070000027B0300000428020000062A0000133004005C00000007000011038E698D070000020A02280D00000A6F0E00000A0B160C2B3B0308A3060000020D07097B01000004D70B06081204FE15070000021204077D030000041204097B020000047D040000041104A4070000020817D60C08038E6932BF062A133003003E0000000800001102038E16FE037285040070281300000A030A160B2B210607A3060000020C02087B01000004166AFE0372D1040070281300000A0717580B07068E6932D92A00001330020086000000090000110228190000060A02281B00000A6F1C00000A067B040000045C0B0228090000060C0708363C08067B04000004D90D02281B00000A6F1C00000A09DB13041205FE15080000021205097D05000004120511047D060000041205087D0700000411052A1205FE1508000002120502281B00000A6F1C00000A7D050000041205077D0700000411052AC20203281100000A0204282400000602052822000006020E0428200000060202281B00000A6F1D00000A0428260000062A4602280600000A721F0500706F2600000A2A4A02280600000A721F050070036F2700000A2A4602280600000A722D0500706F2600000A2A4A02280600000A722D050070036F2700000A2A4602280600000A72370500706F0700000A2A4A02280600000A7237050070036F0800000A2A7202280600000A724F050070038C07000001281200000A6F0700000A2A7602280600000A724F050070038C07000001281200000A046F0800000A2A00000013300400A60000000A000011042D34021201FE150D000002120102281B00000A6F1D00000A7D140000041201037D150000041201166A7D1600000407280800002B172A0202281B00000A6F1D00000A28250000060A06043402162A0202281B00000A6F1D00000A0604DB282600000602030203282500000604D72826000006021201FE150D000002120102281B00000A6F1D00000A7D140000041201037D150000041201047D1600000407280800002B172A000013300500AA0000000B000011052D2A021202FE150D0000021202037D140000041202047D150000041202166A7D1600000408280800002B172A020302281B00000A6F1D00000A282B0000060A020328250000060B0605370407053402162A020302281B00000A6F1D00000A0605DB282A00000602030705DB282600000602040204282500000605D72826000006021202FE150D0000021202037D140000041202047D150000041202057D1600000408280800002B172A000013300400650000000C0000110202281B00000A6F1D00000A03282B000006042E02162A0202281B00000A6F1D00000A0305282A000006021200FE150E000002120002281B00000A6F1D00000A7D170000041200037D180000041200057D1A0000041200047D1900000406280900002B172A8E02280600000A7267050070038C07000001048C07000001282800000A056F0800000A2A8A02280600000A7267050070038C07000001048C07000001282800000A6F0700000A2A4602280600000A728B0500706F0700000A2A4A02280600000A728B050070036F0800000A2A7202280600000A729F050070038C07000001281200000A6F0A00002B2A7602280600000A729F050070038C07000001281200000A046F0B00002B2AC20203281100000A020428400000060205283E000006020E04283C0000060202281B00000A6F1D00000A0428420000062A660202282C00000602281B00000A6F1C00000AD7282D0000062A8E0202281B00000A6F1D00000A283400000626020328340000062602030428430000062A6A020328340000062602042834000006260203040528440000062A0000133003003C0000000D0000110203282E0000060A02030628350000060B07166A36241200067B1B00000407D77D1B000004120002282C0000067D1D000004020306282F000006062A13300200210000000E00001102282C000006047B1D000004DB0A0203284100000606D90B047B1B00000407D72A4A0202281B00000A6F1D00000A28370000062A13300300180000000F0000110203282E0000060A020306283500000602283F0000065C2A4A0202281B00000A6F1D00000A28390000062A00133003001F0000000F0000110203282E0000060A0203062835000006067B1C000004D702283F0000065C2A001330030093000000100000110202281B00000A6F1D00000A28340000060A067B1B00000402283F0000065C0B067B1B00000402283F0000065E0C0207166AFE0372B7050070281300000A1200067B1C000004067B1B000004D708DB7D1C0000041200087D1B0000040202281B00000A6F1D00000A06282F0000060202281B00 [...]

2020-12-31 21:35 UTC, mrtpain requested changes
5 failing tests

1. Invest_CalledForNonFungibleToken_Success
2. Invest_CalledForStandardToken_Success
3. Invest_Fails_If_GetClaim_Call_Fails
4. Invest_Fails_If_GetClaim_Call_Returns_Null
5. Invest_Refunds_Oversold_Tokens

2020-12-31 21:37 UTC, mrtpain commented
Is this an ICO contract or STO contract? Naming should be consistent throughout either way.

2020-12-31 21:42 UTC, mrtpain commented
Cloning and compiling the contract results in a different hash equal to `c73be12ffc41a1e41871bc14aba7b9c2175cbc9e0cfb6fc4c341baaf7550193b`.

2020-12-31 21:48 UTC, mrtpain commented
This PR is missing Mainnet files - will come back and review when PR is fixed up for review.

2021-01-02 12:06 UTC, YakupIpek commented
@mrtpain The project files are up to date now

2021-01-02 19:52 UTC, YakupIpek commented
Sorry i messed up branches. At the moment, this pr contains both testnet and mainnet files for STO Contract. I will close and create seperate pr.

2021-01-02 19:52 UTC, closed without merging